print("Hello World")
print("----------------")
print(5+ 2*3)
print(8//5-3)
print(8+22*2-4)
print(16-3/2+7-1)
print(3**3%5)
print(5+9*3/2-4)
print("---------------")
print("skill drill")
print((5 + 2) * 3)
print((8 // 5) - 3)
print(8 + (22 * (2 - 4)))
print(16 - 3 / (2 + 7) - 1)
print(3 ** (3 % 5))
print(5 + (9 * 3 / 2 - 4))
print(5 + (9 * 3/(2-4)))
print("--------------")
counties = ["Arapahoe", "Denver", "Jefferson"]
print(counties)
print(counties[0])
print(counties[2])
print(counties[-2])
print(len(counties))
print(counties[0:2])
print (counties[0:3])
print(counties[2:3])
print(counties[1:2])
print(counties[0:3])
print(counties[1:3])
print(counties[1:])
print(counties.append("El Paso"))
print(counties)
print(counties.insert(2, "El Paso"))
print(counties)

print("------------------")
print(counties.remove("El Paso"))
print(counties)
print("incorrect--------next try")
counties.insert(2, "El Paso")
print(counties)
print("Attempting to get list back to 5 counties")
print(counties)
print("After several attempts to fix my error, I erased the line of code that created the error")
print(counties)
counties.remove("El Paso")
print(counties)
print(counties[0:1])
print(counties[0:2])
counties.insert(2, "El Paso")
print(counties)
counties.remove("El Paso")
print(counties)
